baseURL = 'https://jamikal.xyz'
languageCode = 'en-us'
title = "Jamikal Hall"
theme = 'archie'
[params]
    mode = "auto"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[taxonomies]
   tag = "tags"