baseURL = 'https://jamikal.xyz'
relativeURLs = "True"
languageCode = 'en-us'
title = "Jamikal Hall"
theme = 'archie'

[params]
    mode = "toggle"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[taxonomies]
   tag = "tags"